package io.hari.demo.service;

import io.hari.demo.dao.BaseDao;
import io.hari.demo.dao.SeatLockDao;
import io.hari.demo.entity.SeatLock;
import io.hari.demo.entity.Show;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/**
 * @Author Hariom Yadav
 * @create 02-03-2021
 */
@Service
public class ShowService extends BaseService<Show> {

    @Autowired
    SeatLockDao seatLockDao;

    public ShowService(BaseDao<Show> showDao) {
        super(showDao);
    }

    @Override
    public Show save(Show show) {
        final Show show1 = super.save(show);//we will get id generated by JPA
        show1.getSeats().forEach(seat -> {
            final SeatLock seatLock = SeatLock.builder().showId(show.getId())
                    .seatId(seat.getId()).lockStatus("available").build();
            seatLockDao.save(seatLock);
        });
        return show1;
    }
}
